package com.example.campusnest.entity;

import com.example.campusnest.utils.Role;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
@Entity

public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long uid;
    @Column(nullable = false, name = "Name")
    private String name;
    @Column(nullable = false, unique = true, name = "Email")
    private String email;
    @Column(name = "Password", nullable = true)
    private String password;
    @Column(name = "Phone", nullable = true)
    private String phone;
    @Column(name = "Role", nullable = false)
    private Role role;

    // Constructors, getters, and setters can be generated by Lombok
    // or manually defined if needed.
    public User() {
        // Default constructor
    }
}
